// Lang: C11 is needed for fopen_s
// This program amalgamates binary files (blobs) into a single text file.
// The output file is a text file that contains an array of the blobs
// along with C source code for the blob data as static arrays.

#include <errno.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>

#define NVMSIZE 0x10000
#define MAXBLOB 15

/**
const uint8_t __attribute__((section(".my_blob"))) myblob[] = { ... }

A "__attribute__((section(".my_data")))", which is a GCC extension used to
position the data in a specific memory section, is included in the arrays if
the file extension is ".gcc". Otherwise, it is omitted for portability.
*/

uint8_t NVM[NVMSIZE];
char blobnames[(MAXBLOB+1) * 256] = {0};
int blobcount = 0;

// Function to extract the filename from a full path
const char* get_filename(const char* path) {
    // Find the last occurrence of '/' (Linux/macOS)
    const char* filename = strrchr(path, '/');
#if defined(_WIN32) || defined(_WIN64)
    // If on Windows, also check for the backslash '\'
    if (!filename) {
        filename = strrchr(path, '\\');
    }
#endif
    // If a separator was found, move the pointer past it; 
    // otherwise, the path itself is just the filename.
    return filename ? filename + 1 : path;
}

int main(int argc, char* argv[]) {
    blobcount = argc - 2;
    if (argc < 1) {     // argv[1] = output
        printf("No output file specified.\n\n");
    help:   
        printf("Usage: bin2c outfile [blob0] [blob1] ...");
        return 1;
    }
    if (argc < 2) {     // argv[2,3,4...] = inputs
        printf("No bin files specified.\n\n");
        goto help;
    }
    if (blobcount > MAXBLOB) {
        printf("Too many blobs.\n\n");
        goto help;
    }
    FILE* fin = NULL;
    FILE* fout = NULL;
    char* filename = argv[1]; // output file (path)
    errno_t err = fopen_s(&fout, argv[1], "w");
    if (err != 0) {
        printf("Cannot write file %s\n", filename);
        return 2;
    }
    printf("Generating file %s\n", filename);
    fprintf(fout, "#include <stdint.h>\n");
    fprintf(fout, "// Auto-generated by bin2c, do not edit.\n\n");

    const char* ext = strrchr(filename, '.');

    // Compare the extension (case-sensitive)
    int isGCC = (ext != NULL && strcmp(ext, ".gcc") == 0);

    for (int i = 0; i < blobcount; i++) {
        filename = argv[i + 2];
        const char* blobname = get_filename(filename);
        errno_t err = fopen_s(&fin, filename, "rb");
        if (err != 0) {
            printf("Cannot open file %s\n", filename);
            return 2;
        }
        memset(NVM, 255, NVMSIZE);
        size_t size = fread(NVM, 1, NVMSIZE, fin);
        fclose(fin);
        printf("Bin file %d = %s, %d bytes\n", i, blobname, (int)size);
        char* dot = strrchr(blobname, '.');
        if (dot != NULL) *dot = '\0';           // clip file extension from blob name
        strcpy_s(&blobnames[i * 256], 256, filename);
        
        fprintf(fout, "const uint8_t ");
        if (isGCC) {
            fprintf(fout, "__attribute__((section(\".blob_%s\"))) ", blobname);
        }
        fprintf(fout, "ba_%s[%d] = {", blobname, (int)size);
        for (int j = 0; j < (int)size; j++) {
			if (j % 16 == 0) fprintf(fout, "\n  ");
            fprintf(fout, "0x%02X", NVM[j]);
            if (j != (size - 1)) fprintf(fout, ",");
        }
        fprintf(fout, "\n}\n");
    }

    if (blobcount) {
        fprintf(fout, "\nconst uint8_t* NVMsections[%d] = {", blobcount);
        for (int i = 0; i < blobcount; i++) {
            fprintf(fout, "\n    (const uint8_t*) ba_%s", get_filename(&blobnames[i * 256]));
            if (i != (blobcount - 1)) fprintf(fout, ",");
        }
        fprintf(fout, "\n}\n");
        fprintf(fout, "#define MAXBLOBIDX %d\n", blobcount - 1);
    }
    fclose(fout);
    return 0;
}
